### ISSUE TITLE
更新到你最新版本报错 说与First Aid不兼容 实际我根本没安装

### ISSUE THREAD

**Issue by LonelyxiyaOVO** [Origins-Eternity/ER-Core#2]
https://mclo.gs/Z64WfNv

**Comment by LonelyxiyaOVO** [comment]
之前1.2.0的beta老版本兼容

**Comment by LonelyxiyaOVO** [comment]
![QQ_1722221230388](https://github.com/user-attachments/assets/ef739e8a-0ba5-4553-b063-bc9cc9f1e060)
这个有问题，beta 1.2.0早期版本没问题

**Comment by Origins-Eternity** [comment]
Fixed in [1796987](https://github.com/Origins-Eternity/ER-Core/commit/17969878440846951d6ca8350f90f3097d6a9cf6)
